name: Solar system workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat--kodekloud

jobs:
  unit-testing:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
